### ISSUE TITLE
Change remote board to use USB-C ports

### ISSUE THREAD

**Issue by ASleepyCat** [HWXLR8/beef-board#79] opened 2024-06-10 13:49 UTC
I have a bunch of USB A-to-C cables lying around, but no A-to-B cables. I figure that A-to-C cables are probably more available for the average person, so it might be better to change the ports to USB-C.

**Comment by HWXLR8** [comment] 2024-06-21 00:55
Closing this as a duplicate of #20

**Closed by HWXLR8** 2024-06-21 00:55 UTC
Labels: enhancement
