### ISSUE TITLE
Digital turntable input

### ISSUE THREAD

**Issue by Mechada2dx** [HWXLR8/beef-board#22] opened 2024-01-09 16:46 UTC
Mostly to play Lunatic Rave 2. Maybe a button combination or a required key to hold while plugging in?

**Comment by HWXLR8** [comment] 2024-01-09 17:30
Could you be a bit more specific as to what the issue is here? Is digital turntable input not working for you?

**Comment by Mechada2dx** [comment] 2024-01-09 17:54
is digital input even a thing with the beef-board?

**Comment by HWXLR8** [comment] 2024-01-09 18:25
@supervaka I remember you tested digital TT and it worked, am I misaken? Referencing the poorly named `analog_turntable.h`

**Comment by HWXLR8** [comment] 2024-02-26 02:03
@ASleepyCat no rush, as usual. Just reassigning.

**Closed** 2024-03-03 17:52 UTC
Labels: enhancement
