### ISSUE TITLE
Lunatic Rave 2 not working with beefboard anymore

### ISSUE THREAD

**Issue by Mechada2dx** [HWXLR8/beef-board#89] opened 2024-07-22 19:06 UTC
Ever since I switched from purple beefboards to the newer black ones, LR2 won't take input from them anymore, digital turntable still works though. I've tried 2 USB mode instead of 1 USB and even tried running LR2 on different computers but still nothing.

**Comment by HWXLR8** [comment] 2024-07-22 19:30
@ASleepyCat there should be no functional difference between these PCB revisions (v4 vs v6), I believe this is a FW regression.

**Comment by ASleepyCat** [comment] 2024-07-23 09:04
@Mechada2dx Could you see if SDVX mode works? Just want to check a theory.

@HWXLR8 Maybe, if there's a handy way of embedding the current commit hash into the fw. I know roxy-firmware shows the board fw version somewhere in roxy-tool (and probably the same with whatever arcin uses for its config tool), but we only have a rudimentary fw flashing tool.

**Comment by ASleepyCat** [comment] 2024-08-03 04:37
I've identified the issue and pushed the fix as part of #88. It's untested though since I can't get to the key config, but button inputs should at least be working again.

**Closed** 2024-08-19 15:45 UTC
Labels: FWBUG
